### ISSUE TITLE
Product Variant Configurator with restrictions.

### ISSUE THREAD

**Issue by angelmoya** [OCA/product-variant#104]
I plan to work in new functionality to be able to rescrict atributes values.

For example, I habe a product with:
- Attribute A, with posible values X, Y, Z
- Attribute B. with posible values 1, 2, 3

But, : 
- if you set Attribute A= X, then Attribute B could be 1, 2
- if you set Attribute A= Y, then Attribute B could be 1, 2, 3
- if you set Attribute A= Z, then Attribute B could be 3

Restrictions must be configurated by product.

**Comment by pedrobaeza** [comment]
@anajuaristi you developed something similar in the past. Did you finish it?

**Comment by pedrobaeza** [comment]
@angelmoya now that Odoo v12 implements this, is it still interesting for you?

**Comment by angelmoya** [comment]
No, we are working on Odoo 12
