### ISSUE TITLE
[10.0] product_variant_supplierinfo JS crash in vendor pricelist

### ISSUE THREAD

**Issue by zeroheure** [OCA/product-variant#110]
Enable Vendor Pricelist in Purchase, Go to Purchases / Purchase / Vendor Pricelist, try to add a variant. It raises the JS error below while accessing the variant selection.

Module works well through product variant view. 

Error: KeyError: 'id'
---------------
http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1585
Retraçage :
__getitem__@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1585:161
__getattr__@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1586:64
__getattribute__@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1385:33
py.PY_getAttr@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1349:174
py.evaluate@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1452:8
py.evaluate@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1447:108
py.evaluate@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1449:96
py.eval@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1454:281
eval_domains/<@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1596:133
_.forEach@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:12:558
_.mixin/</_.prototype[name]@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:69:521
eval_domains@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1595:254
eval_domains/<@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1596:298
_.forEach@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:12:558
_.mixin/</_.prototype[name]@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:69:521
eval_domains@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1595:254
eval_domains/<@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1596:298
_.forEach@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:12:558
_.mixin/</_.prototype[name]@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:69:521
eval_domains@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1595:254
pyeval@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1609:24
eval_arg@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1612:61
ensure_evaluated@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1615:11
call@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1476:1
name_search@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:1751:1038
get_search_result@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:2214:25
source@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:2325:103
_search@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:1461:142
$.widget/</proxiedPrototype[prop]</<@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:1021:328
search@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:1461:8
$.widget/</proxiedPrototype[prop]</<@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:1021:328
$.widget.bridge/$.fn[name]/<@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:1026:13
each@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:370:758
each@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:358:636
$.widget.bridge/$.fn[name]@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:1023:248
render_editable/<@http://abimo:8069/web/content/13475-32770e5/web.assets_backend.js:2320:1041
dispatch@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:637:378
add/elemData.handle@http://abimo:8069/web/content/13433-04fa24e/web.assets_common.js:610:151

**Comment by pedrobaeza** [comment]
This is working on runbot, so it should be a choke with some other module. Please try on a clean installation.

**Comment by zeroheure** [comment]
Please re-open, it doesn't work on runbot neither (just tried). You are confused with vendor pricelist.
To test, enable products variants and vendor pricelists (Purchase > Settings > Purchase Order >  Vendor Price > "Allow using and importing vendor pricelists").
After that, go to Purchase > Vendor Pricelists, choose one, modify and click in the Product variant  selector. It crash with  an "Odoo Client Error".

**Comment by Baton4986** [comment]
Can confirm this. Any Ideas?
