### ISSUE TITLE
[10.0] product_variant_supplierinfo doesn't seem to work on product form

### ISSUE THREAD

**Issue by zeroheure** [OCA/product-variant#111]
Step:
Modify a product form, add a supplier, select product's variant, fill all the field, save supplier info and product form. When re-opening, one can see that product's variant in the supplier info form is gone, the supplier infos looks set for the product template.
Opening the variant form, one can see that supplier infos are set as a variant template.

May be this is intended, in this case it' a UI problem : the select variant field shouldn't be available in the product supplier form.

**Comment by pedrobaeza** [comment]
Well, it can be a UX glitch, but it's clear that if you provide a variant, then it should be on the variant supplierinfo list.

**Comment by zeroheure** [comment]
Not for my users ! :-)

**Comment by pedrobaeza** [comment]
OK, then you can propose an improvement. Note that v11 already includes this feature natively. They show the same list (not 2) with the column "Product Variant" filled or not depending on the selected variant.

**Comment by zeroheure** [comment]
I will certainly try to improve.

**Comment by wpichler** [comment]
I can confirm that this module does not work as expected. Default Odoo v10 product.supplierinfo do already have product_id in supplierinfo. But the field is invisible by default. So the only thing this module would have to do - is to remove the invisble attribute from the form. And the rest will work as expected.

I will create a PR for this.

**Comment by wpichler** [comment]
The current module also adds extra lists on product form for variant vendors and template vendors - this is not needed in my opinion - any use case for this ?
