### ISSUE TITLE
[11.0][sale_variant_configurator] Product configured values dissapear after saving SO

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/product-variant#118]
Hi,
I'm testing this module and i have a rare bug with it:
![deepin-screen-recorder_select area_20181129175100](https://user-images.githubusercontent.com/5034215/49229954-a4afe100-f3ff-11e8-8607-3fde9159af38.gif)
As you can see, i did save the product configuration for the same product with different values, it is clear in the description column, but when I to try to confirm the SO it says that i must to define the attribute values, but why?
So, i review the product configurated values and they are empty. Why?

I did the same process with a from-zero new product without previous variants i hadn't any problem, what's happening here?

**Comment by pedrobaeza** [comment]
Fixed in 4e9c906563e4e30f8b51a80e7fb76f3d2a3281c2

**Comment by SalahAdDin** [comment]
@pedrobaeza Maybe it was solved in the purchase, but i'm working in sale orders.

**Comment by pedrobaeza** [comment]
It has been done in both.

**Comment by SalahAdDin** [comment]
![deepin-screen-recorder_select area_20181204142559](https://user-images.githubusercontent.com/5034215/49438904-b06d2000-f7d0-11e8-9ef3-f24bc247672f.gif)
@pedrobaeza , well, it seems it does not work.
Yeah, i reviewed it three times, and it does not work with a previously created product.

i already updated the modules at least three times and i did review the `xml` code with the debugger.

**Comment by SalahAdDin** [comment]
After saving a new `measure` value, the attribute's field makes some kind of reset, and it loses all values, but the description is fulfilling correctly.

**Comment by pedrobaeza** [comment]
Of course it's not working, because you are creating the attribute value on the fly, and that's another different issue (not issue, but not implemented feature actually).

**Comment by SalahAdDin** [comment]
@pedrobaeza is that feature in progress right now? We choose this alternative because of that feature.

But, if we create a new product we can handle values on the fly without any problems.

**Comment by pedrobaeza** [comment]
How many times I have to say that yes?

**Comment by SalahAdDin** [comment]
I reviewed that, and yes, after creating a new value on the fly all attribute values are not saved.

**Comment by pedrobaeza** [comment]
Again the loop: https://github.com/OCA/product-variant/issues/118#issuecomment-444086559
