### ISSUE TITLE
[11.0][sale_variant_configurator] Configurator does not save attribute values for product

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/product-variant#119]
Hi,

I am geting other problem with the variant configurator:
![deepin-screen-recorder_select area_20181204142559](https://user-images.githubusercontent.com/5034215/49440206-14451800-f7d4-11e8-8ed1-e3048dbe541a.gif)

When i create a new value for the attribute it is not saved related to the value, so, i cannot choose it again the next time, it forces us to create that value again, but it brings us other problem:
![deepin-screen-recorder_select area_20181204145737](https://user-images.githubusercontent.com/5034215/49440559-080d8a80-f7d5-11e8-91f5-0f7fe77b214d.gif)

It is because of the value already exists:
![noguardavalores](https://user-images.githubusercontent.com/5034215/49440478-d694bf00-f7d4-11e8-8234-5167d33c0e11.png)

The idea is getting the current values in the product as much as possible.

How can we do it?

**Comment by pedrobaeza** [comment]
This can't be done for now, as it requires to link the newly created attribute value to the product template. We have already faced this, and investigating the solution.

**Comment by SalahAdDin** [comment]
@pedrobaeza Are you working right now in it?

**Comment by pedrobaeza** [comment]
Yes

**Comment by SalahAdDin** [comment]
Well, how can we help with it?

**Comment by pedrobaeza** [comment]
When it's ready, I'll ask you to review the PR.

**Comment by pedrobaeza** [comment]
Fixed in #122
