### ISSUE TITLE
[11.0][sale_variant_configurator] Remose the user interface

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/product-variant#120]
Hi,

I'm seeing the current interface and i think it could be better:
![deepin-screen-recorder_select area_20181204142559](https://user-images.githubusercontent.com/5034215/49440948-23c56080-f7d6-11e8-9bbc-daf72a3879bd.gif)

It is not needed to handle all line product in the new view, it just requires having a select box to select the product and the product's attribute fields. Also, creating a new attribute value does not require a new form since the attribute must to be the current attribute and the other fields(sequence and attribute sequence) can be filled automatically.
 
What do you think about that?

**Comment by pedrobaeza** [comment]
Why do you put again and again the same video?

It's done this way on purpose for a lot of reasons:

* Guide the introduction of each attribute isolatedly. Other way, it would be very difficult to recognize each one.
* You don't have to deal with multiple selection of several values for the same attribute
* Not all attribute must be filled and this way it's very easy to be recognized.

**Comment by SalahAdDin** [comment]
But, at least the attribute value's form is not required, because, if you are creating a new value for a determinate attribute, you should not choose it again, the system should fill it automatically.

**Comment by pedrobaeza** [comment]
I don't get what do you mean with that.

**Comment by SalahAdDin** [comment]
Actually, I think the form for purchases is more aesthetic than the sale order form:
![esteestamejor](https://user-images.githubusercontent.com/5034215/49444962-b9b2b880-f7e1-11e8-9462-afcca8fb01de.png)

Como me puedo explicar, cuando creamos un nuevo valor para el atributo, este nos envía a un formulario nuevo donde creamos ese nuevo valor, pero aquí debemos elegir el atributo al cuál le vamos a crear un valor, pero por qué? Este debería ser elegido automáticamente, desde que el formulario se lanza desde un atributo existente; es innecesario volver a elegir el atributo.

**Comment by pedrobaeza** [comment]
The idea is to not go to that popup form, but directly choose "Create" option, not "Create and edit...".

**Comment by SalahAdDin** [comment]
I did it, but it triggers the _Create and Edit_ popup.

**Comment by pedrobaeza** [comment]
Yeah, but this is current situation, not the final one.

**Comment by SalahAdDin** [comment]
Hi, i have a possible suggestion:

![deepin-screen-recorder_select area_20181206123226](https://user-images.githubusercontent.com/5034215/49575138-0b2e8500-f953-11e8-8a4d-bb26eda280c9.gif)
In case we are not using the [purchase_variant_configurator_on_confirm](https://github.com/OCA/product-variant/tree/11.0/purchase_variant_configurator_on_confirm) module, we have to create yes or yes the product immediately (check on `create product now!`, otherwise, we will have an error alert and we will not be able to save the line.

**Comment by pedrobaeza** [comment]
That's on purpose: if you don't have the product, you can't save, so:

1. Create the product.
2. Select an existing product.

**Comment by SalahAdDin** [comment]
In this case, if we don't install `on_confirm` module, i think it has the sense that by default the system creates the product without checking the field `create_product_now`

**Comment by pedrobaeza** [comment]
That's a safe-guard IMO for avoiding auto-creation when it's expected to have a recognized product. @sbidoul and his team designed this this way.
