### ISSUE TITLE
[11.0] Some inconsistencies in the views.

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/product-variant#124]
I'm looking and comparing the views and i found some problems with them:
![vistasdelconfigurador](https://user-images.githubusercontent.com/5034215/49513903-80428180-f8a3-11e8-99c7-2bc933c747d4.png)

**Description:** when the user is looking in the **PO** or **SO** it wants to know what product and what attributes it has, that's why the description field in **SO** is the most adequate for a view. That field in **PO** shows the reference code, while users want to know more clear information.

**Product Template:** it can be showed too in the **PO** view, or in neither of the two.

**Product:** It can be shown in both, but while in **PO** is showed(it shows just for products that have previously set attribute values https://github.com/OCA/product-variant/issues/125), it is blank in the **SO**.

I don't know what is the approach behind this differences but i think this changes could be good.

**Comment by pedrobaeza** [comment]
It's not inconsistency: product won't be filled if it still doesn't exist. When confirming the PO, you'll have it. You can create it on the fly without the module `purchase_variant_configurator_on_confirm`.

**Comment by SalahAdDin** [comment]
I'm not using `purchase_variant_configurator_on_confirm`.
