### ISSUE TITLE
[11.0] Configurator does not show the product variant name correctly

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/product-variant#125]
Testing this module I found another issue:

![deepin-screen-recorder_chromium_20181205154900](https://user-images.githubusercontent.com/5034215/49514680-cdbfee00-f8a5-11e8-9d9f-8bb13bde431c.gif)
As you can see, if you put some default attribute values in the product variants the configurator will show the product variant name, and just with the first attribute's value, but if the product hasn't any previously set attribute value, I will just show the product template name.

It happens with all lines related to that product in **PO** and in **SO**.

Why?

**Comment by pedrobaeza** [comment]
Again the same thing... it's all about the creation on the fly. Please stop hammering about the same question.

**Comment by SalahAdDin** [comment]
Yeah, i'm seeing that the name (description) is correct in the creation, but after that, the name becomes the default code plus the template name.

On fly works at least in a half-part, we can create values for attributes on the fly only in products created after installing the module, but we cannot edit them:
![deepin-screen-recorder_select area_20181205173656](https://user-images.githubusercontent.com/5034215/49520532-8725c000-f8b4-11e8-9b99-74e3267e7fda.gif)

**Comment by SalahAdDin** [comment]
Actually, i don't understand how does it work.

I did some experiments in the BoM:
![deepin-screen-recorder_select area_20181205175128](https://user-images.githubusercontent.com/5034215/49521675-06b48e80-f8b7-11e8-9332-e38b92cd3024.gif)
