### ISSUE TITLE
[11.0] sale_order_variant_mgmt not using price or discount from pricelist

### ISSUE THREAD

**Issue by 2EyeTec** [OCA/product-variant#131]
when adding products to sale order with a different price or a discount defined in a price list, this price is not used but only the standard price

**Comment by pedrobaeza** [comment]
You can see in this line:

https://github.com/OCA/product-variant/blob/968fb839601c3b4b9fe20e0f8c28571301386297/sale_order_variant_mgmt/wizard/sale_manage_variant.py#L88

That the same behavior that you get adding the line by hand in UI is mimicked here, and certainly I'm using the module without the problem you mention.

Maybe some kind of custom module? Any way, closing as no valid.

**Comment by 2EyeTec** [comment]
As far as I can tell, you're right if the discount policy is "Discount included in the price", then the price defined in the price list is used. But if the discount policy is "Show public price & discount to the customer" the relevant discount percentage is not added to the line, only the price! How are you using the module?

....and Happy New Year ;-) !

**Comment by pedrobaeza** [comment]
It's possible that there other involved onchange around the same field. Then you should fix it playing all the onchanges in the code I mention.
