### ISSUE TITLE
[10.0][sale_variant_configurator]: Error inherit super

### ISSUE THREAD

**Issue by igallart** [OCA/product-variant#135]
Hello, there are any errors with the last update in sale_variant_configurator.

https://github.com/OCA/product-variant/blob/785c20b0786e3c08146871f4e49fffc3c438ad38/sale_variant_configurator/models/sale_order.py#L80

https://github.com/OCA/product-variant/blob/785c20b0786e3c08146871f4e49fffc3c438ad38/sale_variant_configurator/models/sale_order.py#L84

https://github.com/OCA/product-variant/blob/785c20b0786e3c08146871f4e49fffc3c438ad38/sale_variant_configurator/models/sale_order.py#L129

The problem is that the instance is SaleOrder, and in this class the name is SaleOrderLine.

**Comment by pedrobaeza** [comment]
You are totally right. My bad backporting a thing from v11, where you can put only `super()`.

Fixed in https://github.com/OCA/product-variant/commit/33cfb3922972af5d90a25c1167af4ecbaf69eb97
