### ISSUE TITLE
product_variant_default_code: issue

### ISSUE THREAD

**Issue by omalbastin** [OCA/product-variant#140]
Admin user who is having the "Product Default Code Behavior" group set a reference mask for a product template. Then another user without the "Product Default Code Behavior"  security group make changes to any field other than attribute_line_ids, reference_mask, code_prefix etc can trigger the default_code generation using the default_reference_mask

**Comment by pedrobaeza** [comment]
I don't get what you mean

**Comment by omalbastin** [comment]
https://github.com/OCA/product-variant/blob/11.0/product_variant_default_code/models/product.py#L127


If a user who is not having "Product Default Code Behavior" group makes any change to any other fields it will recompute the default_code for every variant with new reference_mask generated with self._get_default_mask() method

**Comment by pedrobaeza** [comment]
Do you mean incorrect parenthesis? Please do a PR amending that.

**Comment by omalbastin** [comment]
That or condition is causing the problem. I will create a PR
