### ISSUE TITLE
[10.0] product_variant_configurator conflict with Inventory Adjustments

### ISSUE THREAD

**Issue by igallart** [OCA/product-variant#151]
The product_id field https://github.com/OCA/product-variant/blob/10.0/product_variant_configurator/models/product_configurator.py#L31 and https://github.com/OCA/product-variant/blob/10.0/product_variant_configurator/models/product_product.py#L10 does conflict with adjustmen inventary:

ProgrammingError: column reference "product_id" is ambiguous
LINE 1: SELECT product_id, sum(qty) as product_qty, location_id, lot...

https://github.com/OCA/OCB/blob/10.0/addons/stock/models/stock_inventory.py#L266

**Comment by pedrobaeza** [comment]
The problem is in Odoo itself: https://github.com/odoo/odoo/pull/34387

**Comment by igallart** [comment]
@pedrobaeza, are very fast! Thank you.
