### ISSUE TITLE
[11.0] product_variant_configurator: When activating sales message, the name in the sales order is False

### ISSUE THREAD

**Issue by deivislaya** [OCA/product-variant#153]
**Impacted versions:** 11.0 e

**Steps to reproduce:**

1. Activate the warning when Selling this Product
2. create sale order with the product with demo user

**Current behavior:**

When activating sales message in the product, the name in the sales order is False with demo user

**Expected behavior:**

When activating the message for sale from the product, obtain the product name correctly in the sales order with any user

**Video/Screenshot link (optional):**

https://youtu.be/qshXIEjj6xg

**Comment by pedrobaeza** [comment]
Well, in fact this is a side effect, as nothing should be put there. Are you going to do a PR for this?
