### ISSUE TITLE
[13.0][14.0] Wrong price on SO when using UOM with ratio

### ISSUE THREAD

**Issue by jlaloux** [OCA/product-variant#259]
## Module
product_variant_sale_price

## Describe the bug
Price is not correct on SO on a product configured with a different UOM than the base UOM and we change the UOM to an other UOM of same type on SO

## To Reproduce
**Affected versions**: 13.0, 14.0 (not tested on other versions)

1. Install modules: sale, product_variant_sale_price
2. Create a new UOM "box of 2000 units" with :
             - Category: "Unit"
             - Type: "Bigger than the reference Unit of Measure"
             - Bigger Ratio: "2000"
![image](https://user-images.githubusercontent.com/7678583/167636751-e4b520c8-8049-4e30-ab3c-c5cdd3ef7c3a.png)

3. Create a product with : 
             - Sales price: 2000000
             - Unit of measure: Box of 2000
![image](https://user-images.githubusercontent.com/7678583/167637232-95f0133b-6a9d-4383-aa66-b857a6b5cb06.png)

4.  Create a SO and set product in a sale order line
![image](https://user-images.githubusercontent.com/7678583/167637439-2d8654e2-0ee8-4ea0-ab81-6c12df916ec9.png)

Price is correct
6. Change UOM to "Unit"
![image](https://user-images.githubusercontent.com/7678583/167638086-290ef42e-3638-45f1-80fd-7c409c05d0d3.png)

Price is wrong

**Expected behavior**
Price should have been "2000000 euro / 2000 (ratio)"=1000 like on standard Odoo

**Additional context**
Error seems to be in functions "_compute_lst_price", "_compute_list_price", "_inverse_product_lst_price" on product.product
If you open the product from the sale orrder line with "unit" UOM, you'll see "Public price" already computer with the UOM set on sale order line 
![image](https://user-images.githubusercontent.com/7678583/167639062-4409302e-5625-4bcc-85e1-258380ea9e49.png)

**Comment by redapureskill** [comment]
Same with V15 :(

**Comment by Olimalt85** [comment]
hi, 
I met the same problem recently (in odoo V14) and i changed the _compute_list_price like this :  

```
    def _compute_list_price(self):
        uom_model = self.env["uom.uom"]
        for product in self:
            price = product.fix_price or product.product_tmpl_id.list_price
            if self.env.context.get('uom'):
                # i check with get because sometimes the key 'uom' is in context
                # but the value is False
                context_uom = uom_model.browse(self.env.context.get('uom'))
                price = context_uom._compute_price(
                    price, context_uom)
            product.list_price = price
```

For the moment it is working for me ^^

**Comment by flotho** [comment]
same here in v14
