### ISSUE TITLE
code_prefix added twice when sanving product.template

### ISSUE THREAD

**Issue by jcambert** [OCA/product-variant#299]
## Module
OCA / product-variant

## To Reproduce
on version 16.0 file product.py

1. while _compute_reference_mask is called twice when saving product,when having code_prefix, code_prefix also added twice, line 119 on product.py

**Expected behavior**
check that reference_mask didn't start with code prefix on line 126
eg => elif not automask and rec.code_prefix and not rec.reference_mask.startswith(rec.code_prefix):

**Comment by ajjayymahato** [comment]
@jcambert Hi there! I would like to work on this issue. Is this issue still open? Can you please assign this issue to me!

**Comment by jcambert** [comment]
Sorry, but i am not able to do this..
it seem that i have no right 
![Capture d’écran 2023-09-29 133904](https://github.com/OCA/product-variant/assets/1908336/c3ea3265-0778-42bd-b701-df56443c9c77)

**Comment by ajjayymahato** [comment]
@jcambert so is this issue open still?

**Comment by jcambert** [comment]
yes, but i dont know how to fix the assignee
as you can see , there is no button to do this

**Comment by ajjayymahato** [comment]
@jcambert Do you have access to merge PR? If I make one?

**Comment by jcambert** [comment]
I don't have

**Comment by diggy128** [comment]
Any update on this?
It also happens in v15 community
