### ISSUE TITLE
[Question] Why is name_search used at Dimension type?

### ISSUE THREAD

**Issue by atchuthan** [OCA/product-variant#5]
The name_search available at Product variant dimension type

class product_variant_dimension_type(orm.Model):
    _name = "product.variant.dimension.type"

```
def name_search(self, cr, uid, name='', args=None, operator='ilike', context=None, limit=None):
    if not context.get('product_tmpl_id', False):
        args = None
    return super(product_variant_dimension_type,
                 self).name_search(cr, uid, '', args, 'ilike', None, None)
```

The name_search should have been

```
def name_search(self, cr, uid, name='', args=None, operator='ilike', context=None, limit=None):
    if not context.get('product_tmpl_id', False):
        args = None
    return super(product_variant_dimension_type,
                self).name_search(cr, uid, name=name, args=args, operator=operator, context=context, limit=limit)
```

Why is the parameter values cleared at the return statement of NAME_SEARCH method?

What is the reason to clear the DOMAIN or args in the name_search?
Is this done to handle some special case?

I had raised a question @ launchpad(https://answers.launchpad.net/openerp-product-variant/+question/253433).  Since, the Management of the project has been moved to GitHub, I am resubmitting the question here.

**Comment by gurneyalex** [comment]
I have no idea about the reason. If you feel this is wrong, please send a PR and make sure to include a test showing why the original code is wrong.

**Comment by pedrobaeza** [comment]
Closing as outdated.
