### ISSUE TITLE
[9.0] product_variant_supplierinfo doesnt update successfully

### ISSUE THREAD

**Issue by rodoo9** [OCA/product-variant#53]
Hi all,

module: https://github.com/OCA/product-variant/tree/9.0/product_variant_supplierinfo

It seems that when you create a **new purchase** of a variant:
1) Do not create the variant supplier with the price and the supplier of the order
2) In case of the variant supplier exist, the variant supplier is not updated with the new price

**Comment by pedrobaeza** [comment]
That part is not covered in the module. You need to develop a new module purchase_product_variant_supplierinfo that covers purchase related stuff, and ideally contribute it here.
