### ISSUE TITLE
[sale_order_variant_mgmt]Selecting template by entering reference

### ISSUE THREAD

**Issue by blutecsolutions** [OCA/product-variant#59]
_First of all a big thanks for the impressive work,_

MODULE: https://www.odoo.com/apps/modules/10.0/sale_order_variant_mgmt/
In this step:
**Press "Add variants" button located in the upper right corner of the "Order Lines" tab.**
It would be great if you could possibly select the product template in this module by entering the product internal reference as well as selecting from drop down 👍

**Comment by pedrobaeza** [comment]
This is not something to do in this module, but to modify on name_search of the product template.
