### ISSUE TITLE
[10.0] product_variant_template_data module

### ISSUE THREAD

**Issue by tafaRU** [OCA/product-variant#64]
Further to  https://github.com/OCA/product-variant/pull/42#issuecomment-311014246 I started working at https://github.com/tafaRU/product-variant/tree/10.0-add-product_variant_template_data

Before to continue I'd like to be sure that I'm working properly, so that I share my Todo list as follows:

Todo List
========
- [x] migrate features of https://github.com/OCA/product-variant/tree/8.0/product_variant_sale_delay
- [x] ~~migrate features of https://github.com/OCA/product-variant/tree/8.0/product_variant_storage_location~~ (as https://github.com/OCA/product-variant/issues/64#issuecomment-313100763)
- [x] ~~migrate features of https://github.com/OCA/product-variant/tree/8.0/product_variant_weight~~ (as https://github.com/OCA/product-variant/issues/64#issuecomment-313440671) 
- [x] create the new module `product_variant_template_data` merging inside of it all the features of the three modules above mentioned

I won't move https://github.com/OCA/product-variant/tree/8.0/product_variant_available_in_pos
as its data is more focused on `point_of_sale`.
While I have doubts about also moving https://github.com/OCA/product-variant/tree/8.0/product_variant_cost_price and https://github.com/OCA/product-variant/tree/8.0/product_variant_sale_price.

Your feedback are welcome!

**Comment by eLBati** [comment]
As ```product_variant_cost_price``` and ```product_variant_sale_price``` have a bit more complex logic, I agree on keeping them separated

**Comment by tafaRU** [comment]
`product_variant_storage_location` doesn't need to be migrated as highlighted at
https://github.com/OCA/product-variant/issues/40#issuecomment-313098534

**Comment by tafaRU** [comment]
`product_variant_weight`: `weight_net` field was removed since 9.0 as written at https://github.com/OCA/OpenUpgrade/blob/9.0/addons/product/migrations/9.0.1.2/openupgrade_analysis_work.txt#L137

**Comment by tafaRU** [comment]
`product_variant_weight`: `weight` field is already managed at product level.
And therefore, `product_variant_template_data` becomes useless,  so I would cover to migrate `product_variant_sale_delay`.
@pedrobaeza, do you agree?

**Comment by tafaRU** [comment]
Further to my previous message I'm working on https://github.com/tafaRU/product-variant/commits/10.0-mig-product_variant_sale_delay

**Comment by tafaRU** [comment]
I think it's better to continue on `product_variant_template_data` as so that it will be more opening for new further additions.

**Comment by pedrobaeza** [comment]
I prefer to have all that fields together in one place, as the logic is not too much complicated any way.
