### ISSUE TITLE
[9.0/10.0] sale_variant_configurator: does not take into account the extra price of the attributes

### ISSUE THREAD

**Issue by DarioLodeiros** [OCA/product-variant#68]
When you create product variants with extra price set in its attributes, if you have installed product_variant_configurator this extra price are not reflect in the product variant price

**Comment by pedrobaeza** [comment]
We are not maintaining that version anymore, but check the solution given in the commented on https://github.com/OCA/product-variant/pull/70#issuecomment-348703535 and applied in v10.
