### ISSUE TITLE
10.0 sale order variant mgmt issue

### ISSUE THREAD

**Issue by msadiq1411** [OCA/product-variant#79]
Thanks for the effort for this amazing module.
Ive just noticed that the quantity total sum in the matrix doesnt calculate the accumulate of quantities between attribute values .
TOTAL SHOWING ZERO 0
Screenshot:
htps://ibb.co/gEdPBa

**Comment by pedrobaeza** [comment]
Please try on runbot to see if the problem also reproduces.

**Comment by msadiq1411** [comment]
Thanks for proposing this solution, which proved to be helpful, but the issue is that the total is calculated only after clicking transfer to order button in matrix, then opening up the add variants. 
As shown in Screenshot, I added 3 over existing 5 and 10 -  but total showed only 15, instead of 18.:
https://ibb.co/f6PHEv

**Comment by msadiq1411** [comment]
Another screen shot to explain further :

https://ibb.co/jDgjcF

As you can see total shows zero, until button is clicked and table is re opened

**Comment by pedrobaeza** [comment]
Moving the issue to https://github.com/OCA/web/issues/697, that it's where it should be (but no solution for now will be provided).
