### ISSUE TITLE
[10.0] Failed to write on multi record when product_default_variant_code is installed

### ISSUE THREAD

**Issue by sebastienbeau** [OCA/product-variant#92]
@bealdav @pierrickbrun @daniel-CA  @chienandalu  @gdgellatly  @pedrobaeza 

I have detected an issue with the module product_default_variant_code
Indeed the write on multi-record is broken. 

If you take a look here : https://github.com/OCA/product-variant/blob/10.0/product_variant_default_code/models/product.py#L129 the code check "self.attribute_line_ids" or "self" can be a list of record.

I do not have the time to propose I fix right now. But maybe next week

**Comment by gdgellatly** [comment]
@sebastienbeau I don't really see a case where this field should be written to multiple records. Effectively updating multiple product templates to have the same mask?

Anyway if it helps this is how I handled the case. https://github.com/odoonz/odoonz-addons/blob/11.0/product_code_builder/models/product_template.py#L57

**Comment by pedrobaeza** [comment]
Any news about this?

**Comment by bealdav** [comment]
Same feedback with another use case when I delete products

```
File "/workspace/parts/product-variant/product_variant_default_code/models/product.py", line 129, in write
    if self.attribute_line_ids:
  File "/workspace/parts/odoo/odoo/fields.py", line 904, in __get__
    record.ensure_one()
  File "/workspace/parts/odoo/odoo/models.py", line 4823, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: product.template(26, 27, 28, 29)
```

**Comment by Daniel-CA** [comment]
@bealdav How did you get this error? Just deleting the selected product_templates?

**Comment by bealdav** [comment]
yes

**Comment by bealdav** [comment]
I will fix it

**Comment by pedrobaeza** [comment]
Closing as the PR fixing it was merged.
