### ISSUE TITLE
[10.0] product_variant_default_code - product.template default_code empty

### ISSUE THREAD

**Issue by PierrickBrun** [OCA/product-variant#93]
Odoo deletes the default_code when a product.template has more than 1 variant.

I think this would be better to have the default_code still present on a multiple variants template when using this module because the template has the code_prefix which is the template's default_code

That way, the code_prefix would be visible in the tree view instead of an empty column

Here is Odoo's code I would like to change: 

```

@api.depends('product_variant_ids', 'product_variant_ids.default_code')
    def _compute_default_code(self):
        unique_variants = self.filtered(lambda template: len(template.product_variant_ids) == 1)
        for template in unique_variants:
            template.default_code = template.product_variant_ids.default_code
        for template in (self - unique_variants):
            # template.default_code = ''
            template.default_code = template.code_prefix
```

Any thoughts about this ?

**Comment by pedrobaeza** [comment]
Please open a PR to see the before and after of your change, so we can decide.
