### ISSUE TITLE
[10.0] Discusse on improving the user experience of  product_variant_default_code

### ISSUE THREAD

**Issue by sebastienbeau** [OCA/product-variant#96]
Hi I face to a UI issue with the module product_variant_default_code

When you try to create an new template, odoo will show you the "Internal Reference" see the capture
![image](https://user-images.githubusercontent.com/1164578/37903253-8380c844-30f7-11e8-91ae-06573eefe646.png)

As the general information is the first tab the user will start here and fill the "Internal Reference" with the code he want to affect for this template.
Then the user will fill the information on the variant 'color, size'...

![image](https://user-images.githubusercontent.com/1164578/37903266-8a4e2c20-30f7-11e8-8240-148159f1761e.png)

After saving the user expect to have the variant generated with the right code, but instead the code on the template have been remove !

![image](https://user-images.githubusercontent.com/1164578/37903278-8fdfdcba-30f7-11e8-99b7-7ddc15c4bbbe.png)

In reality the code have been not remove because the user have filled the "internal_reference" (that we do not used in case of product.template with multiple variant) and now we are showing the "code_prefix". But in the point of view of the end user is very unuser-friendly.

I think we should always show the "code_prefix" then
- when we create a template with multiple variant we will have no issue
- when we create a template without variant we should copy the "code_prefix" inside the "internal_reference" of the product.product

In case we create a product.product directly (or we modify it) we should also update the code_prefix with the value of the "internal_reference"

Moreover when you are in the tree view of the product_template. We should show the prefix_code instead of the internal_reference in order to see the "code" of the template. And also filter on this field

The behavior I describe here was the existing behavior of the version 8 in product_code_builder https://github.com/OCA/product-attribute/tree/8.0/product_code_builder

What do you think?
@bealdav @pedrobaeza @Daniel-CA @gdgellatly @chienandalu @gurneyalex

**Comment by gdgellatly** [comment]
+1 from me.  Thats the way I did the original port anyway and how I'm doing
it in 11.  I remember when I did it, I did a full review of both modules, I
based it off product_code_builder, essentially keeping the module, field
names, nomenclature defaults etc for maximum compatibility and then brought
over the good stuff that was different from default_code and made it fit.
Also perhaps we should look at the write method that assigns a default
reference mask (or partcode template, never liked the name reference mask,
too technical) and have it prefix the internal reference if it exists.

**Comment by pedrobaeza** [comment]
Ok for me too.

**Comment by sebastienbeau** [comment]
Thanks for your quick feedback, we will propose a PR today or tomorrow

**Comment by pedrobaeza** [comment]
Closing as there's an opened PR.
