### ISSUE TITLE
[10.0] Product Variant Configurator error unlink 

### ISSUE THREAD

**Issue by apesquero** [OCA/product-variant#97]
odoo.models.unlink: User #1 deleted product.configurator.attribute records with IDs:

Odoo Warning:
Record does not exist or has been deleted.

This error occurs with the module:

https://github.com/apesquero/sale-workflow/tree/10.0/payment_signal

When we change the value of the signal to any other value and save.

Thank you very much

**Comment by pedrobaeza** [comment]
Sorry, but the problem should be in your module, not in the other one.

**Comment by apesquero** [comment]
Can you give me a clue? I'm desperate.

The module is passing the controls in the OCA, and it only gives conflict if I install said module.

Thank you very much.

**Comment by pedrobaeza** [comment]
Try to debug the steps given removing some part of the code to get exactly the portion of code with problems, and come back with that.

**Comment by apesquero** [comment]
I've done that, as far as my knowledge goes, I've reviewed my code, and I think that's not the problem. I'm telling you, it works correctly without product_variant_configurator and my code is very simple. I do not understand the concept of unlink, but it happens before executing my code (or so I think)

**Comment by pedrobaeza** [comment]
You are not even putting the steps to reproduce the problem...

**Comment by apesquero** [comment]
Sorry ... the problem is when you run this api.depends (line 26) when you change payment_signal field.

https://github.com/apesquero/sale-workflow/blob/10.0/payment_signal/models/inherit_sale_order.py

In debugging (I do it step by step with pycharm) does not give problems, when I save, it is when the problem appears.

It only happens when I have products that have variants with the module sale_variant_configurator.

Thank you for your patience

**Comment by pedrobaeza** [comment]
Then it's a problem of the API, the same as I have found here: https://github.com/OCA/commission/pull/151, so no easy solution.

**Comment by apesquero** [comment]
What alternative can I have?

Can I make it not depends field, and use something similar to sale_order_price_calculation?

**Comment by pedrobaeza** [comment]
The problem seems to be with one2many inside one2many shown in the form. Try to modify that in the same way I do in the other PR.

**Comment by apesquero** [comment]
Forgive my clumsiness, I do not have any one2many in my module.

What am I not seeing?

**Comment by pedrobaeza** [comment]
No, the problem is the combination of your onchange with that one2many inside the one2many on the other module.

**Comment by apesquero** [comment]
Thanks, I do not bother you anymore, I'm going to see your code, and see what I get.

Thanks again.

**Comment by apesquero** [comment]
Hi Pedro, I think I have found the solution. The problem is not in the onchange, it really is a problem of the owner_id, which, deletes its value by the property ondelete.

https://github.com/OCA/product-variant/blob/10.0/product_variant_configurator/models/product_configurator_attribute.py

I modified it to "set null" and it seems to work correctly.

Is there a problem that I do not know when making this change? Thank you.

**Comment by pedrobaeza** [comment]
Which line?

**Comment by apesquero** [comment]
20

**Comment by pedrobaeza** [comment]
No, that's correct. Then the problem is that you are removing one record that you shouldn't...

**Comment by apesquero** [comment]
My module does not delete any record, it is deleted when add the product in line order.

In fact, the problem appears simply by creating a "depends" on the "Monetary" field that is not at all related to the products. All in quotation.

You can check my code, it's very short and simple.

https://github.com/apesquero/sale-workflow/blob/10.0/payment_signal/models/inherit_sale_order.py

**Comment by apesquero** [comment]
I think you should modify the PR as improvement or fix.

Do you want me to make a PR as an improvement or fix?

**Comment by pedrobaeza** [comment]
That's not the solution as said. There should be other thing.
