### ISSUE TITLE
[10.0] sale_variant_configurator: does not take into account the extra price of the attributes

### ISSUE THREAD

**Issue by apesquero** [OCA/product-variant#99]
Hello, I have verified that when you select a product (product_tmpl_id) that does not have "product_id", it does not add the price of the variant (price_extra).

![sin-titulo-2](https://user-images.githubusercontent.com/12778835/40071497-37792756-5871-11e8-9e85-fc046c058de5.jpg)

I created the solution in this fix. #98 

But, there are problems with product.pricelist and the option "Show public price & discount to the customer".

![sin-titulo-2](https://user-images.githubusercontent.com/12778835/40558174-c5950d1e-6052-11e8-89fb-eb924da3cd55.jpg)

Error in sql.

This module needs to create deeper modifications.

Thank you

**Comment by pedrobaeza** [comment]
Duplicated of #68
